spring:
  application:
    name: Mechanus

  datasource:
    url: jdbc:postgresql://localhost:5432/mechanus
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api

app:
  seed:
    dnd2024:
      enabled: true